### ISSUE TITLE
Unsplash like modal gallery [feature]

### ISSUE THREAD

**Issue by driptamine** [onderonur/react-router-modal-gallery#1]
How to set background location of modal page to previous parent route, like Unsplash did? 

Emulation:

1. click on photo from feed
2. then click to **another photo** on modal page to watch effect
3. **refresh** page
4. click to **go back** on browser
5. notice the **route of background location** on modal page

**Comment by onderonur** [comment]
Hi! First of all, sorry for the late response.  
I think I understand what you aim. We may add a parameter etc while routing to a modal page and make it have its original parent path, or maybe some custom one. But also, this might mess with the history tracking horribly :)  
This package has a very simple tracking for the history and making it a little bit more flexible might be very useful but also it might be a little hard to maintain too.  
I'm not sure if I will be able to add this feature in a short time. I always appreciate any contribution, so if you have any PR etc to make this feature happen, that would be great too.
Thanks for the idea!
