### ISSUE TITLE
Redirect from code with modal?

### ISSUE THREAD

**Issue by BruceWheaton** [onderonur/react-router-modal-gallery#2]
Not really an issue, but is there a way to use a redirect or history push and get a modal? ModalRedirect or similar? Or would history push ‘do the right thing’?

(My use case is an external trigger that should show a modal, and the ideally be able to switch within the modal, while the background component 
is still active)

**Comment by chaos87** [comment]
I second this.
Unfortunately using history push would cause the background component to rerender.

**Comment by onderonur** [comment]
Hi!

It's been some time since this issue was created, so sorry for that.
But you can programmatically navigate to a route with modal like:
```js
history.push({
      pathname: "/some-modal-route",
      state: { 
            // When you pass modal: true in your location.state,
            // you will be navigated to a modal route.
            modal: true 
      },
});
```

I will add this to `README.md` too.

Thanks!
