### ISSUE TITLE
ModalSwitch inside a BrowserRouter?

### ISSUE THREAD

**Issue by BruceWheaton** [onderonur/react-router-modal-gallery#5]
I have BrowserRouter in my top level, in order to be able to access history & location (seems to be a react-router limitation).

When I go to a ModalRoute, I don't see the current/background component. Is that because of the router? Since I have to put ModalRoutes in the ModalSwitch, and I want to pass props from my app states, it's hard to place at the top level.

Anything else I should check or is that the problem?

**Comment by BruceWheaton** [comment]
Hmm. If I mess with the parent path I get a background but odd routing as I go back and forth (ghost back routing)

**Comment by onderonur** [comment]
Hi there,

First of all, sorry for the late response. I had no opportunity to maintain or enhance this library and with the current react-router changes (v6 and above) it seems like this package can be deprecated now. I would really want to ask for a reproduce of the problem and dig into it. But I don't have much time for this package and it seems like there will be no need for it with the new react-router.

Once again, sorry for my late response and thanks for your interest 🙏
